.PHONY: clean All

All:
	@echo "----------Building project:[ cln_a2b2c4 - Debug ]----------"
	@cd "cln_a2b2c4" && "$(MAKE)" -f  "cln_a2b2c4.mk"
clean:
	@echo "----------Cleaning project:[ cln_a2b2c4 - Debug ]----------"
	@cd "cln_a2b2c4" && "$(MAKE)" -f  "cln_a2b2c4.mk" clean
