.PHONY: clean All

All:
	@echo "----------Building project:[ a2_plus_b2_eq_c4 - Debug ]----------"
	@cd "a2_plus_b2_eq_c4" && "$(MAKE)" -f  "a2_plus_b2_eq_c4.mk"
clean:
	@echo "----------Cleaning project:[ a2_plus_b2_eq_c4 - Debug ]----------"
	@cd "a2_plus_b2_eq_c4" && "$(MAKE)" -f  "a2_plus_b2_eq_c4.mk" clean
